server:
  port: 8888

Spring:
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: "GMT+10"

  # for swagger to parsing package path name in a string
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher