CREATE TABLE article (
     id INT(11) NOT NULL AUTO_INCREMENT,
     author VARCHAR(32) NOT NULL,
     title VARCHAR(32) NOT NULL,
     content VARCHAR(32) NOT NULL,
     create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
     PRIMARY KEY (id)
)  ENGINE=INNODB;